name: Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Spring Boot"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🔧 gh 설치 (for retry)
        uses: cli/cli-action@v1

      - name: 🔄 빌드 아티팩트 다운로드 (최대 5회 재시도)
        run: |
          for i in {1..5}; do
            echo "🔄 다운로드 시도 $i ..."
            gh run download ${{ github.event.workflow_run.id }} -n spring-boot-app -D ./spring-boot-app && break
            echo "⏳ 잠시 대기 후 재시도..."
            sleep 5
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 EC2로 JAR 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "spring-boot-app/*.jar"
          target: "/home/ubuntu/app"

      - name: ⛔ 기존 앱 종료
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[1] 기존 애플리케이션 종료 시도"
            pkill -f "java -jar" || echo "→ 종료할 프로세스 없음"

      - name: 🚀 새 앱 실행 + 헬스체크
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[2] JAR 파일 선택"
            JAR=$(ls /home/ubuntu/app/*.jar | head -n 1)
            if [ ! -f "$JAR" ]; then
              echo "❌ JAR 파일이 없습니다: $JAR"
              exit 1
            fi

            echo "[3] 애플리케이션 실행"
            nohup java -jar "$JAR" > /home/ubuntu/app/app.log 2>&1 &
            disown

            echo "[4] 기동 대기"
            sleep 10

            echo "[5] 상태 확인"
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/)
            echo "→ 응답 코드: $STATUS"

            if [[ "$STATUS" == "200" || "$STATUS" == "302" || "$STATUS" == "401" ]]; then
              echo "✅ 애플리케이션이 정상적으로 실행되었습니다."
            else
              echo "❌ 앱 응답 없음, 로그 출력:"
              tail -n 50 /home/ubuntu/app/app.log || echo "(로그 없음)"
              exit 1
            fi
